version: "3.8"

services:
  app:
    image: ufoac/app:${IMAGE_TAG:-latest}
    container_name: app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./app/logs:/app/logs/
      - ./app/data:/app/data/
      - ./app/conf:/app/config/
    command: [ "Demo!"]
    environment:
      TZ: Asia/Shanghai
      WEB_PORT: 8080
      ENABLE_FLYWAY: true
      PG_HOST: app-database.cvkcyqgesb8e.ap-northeast-1.rds.amazonaws.com
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASS: app2025.OK-=
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: >
        -Xms512m
        -Xmx512m
        -XX:+HeapDumpOnOutOfMemoryError 
        -XX:HeapDumpPath=./data/heapdump.hprof 
        -Dfile.encoding=UTF-8
        -Djava.awt.headless=true
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 700M
    network_mode: host

