spring:
  datasource:
    url: jdbc:postgresql://192.168.47.100:5432/app
    username: postgres
    password: postgres
  flyway:
    enabled: false

logging:
  config: classpath:log/logback-dev.xml
  level:
    root: INFO
    com.demo.app.repository.mapper: DEBUG
