-- H2 schema.sql Only for quick testing
CREATE TABLE IF NOT EXISTS account (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       email VARCHAR(255) NOT NULL UNIQUE,
                                       contract_id VARCHAR(15) NOT NULL,
                                       status VARCHAR(20) NOT NULL CHECK (status IN ('CREATED', 'ACTIVATED', 'DEACTIVATED')),
                                       info VARCHAR(255) DEFAULT '',
                                       version INT DEFAULT 0 NOT NULL,
                                       create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_account_update_time ON account(update_time DESC);

CREATE TABLE IF NOT EXISTS card (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    account_id BIGINT,
                                    rfid VARCHAR(1024),
                                    status VARCHAR(20) NOT NULL CHECK (status IN ('CREATED', 'ASSIGNED', 'ACTIVATED', 'DEACTIVATED')),
                                    info VARCHAR(255) DEFAULT '',
                                    version INT DEFAULT 0 NOT NULL,
                                    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_card_account_update_time ON card(account_id, update_time DESC);
CREATE INDEX idx_card_update_time ON card(update_time DESC);