name: CD Pipeline

on:
  # workflow_run:
  #   workflows: ["CI Pipeline"]
  #   types:
  #     - completed
  #   branches: [main]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image Tag(default:latest)"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd app
            export IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}
            docker compose -f docker-compose.yml up -d --force-recreate --pull always